// SPDX-License-Identifier: GPL-2.0-only
/*
 * tools/bin2c.c
 * Jose A. Perez de Azpillaga <azpijr@gmail.com>, 2026
 * a flat binary, as a C array.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr, "usage: bin2c <name> <in.bin> > out.c\n");
        return 2;
    }
    const char *name = argv[1];
    const char *path = argv[2];

    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        fprintf(stderr, "bin2c: cannot read %s\n", path);
        return 1;
    }

    /*
     * the basename, because the generated file names its source and an
     * absolute path in a comment would make the output depend on where
     * the tree happens to live
     */
    const char *base = strrchr(path, '/');
    base = base != NULL ? base + 1 : path;

    printf("/* generated by tools/bin2c.py from %s, do not edit */\n", base);
    printf("#include <stddef.h>\n");
    printf("#include <stdint.h>\n");
    printf("\n");
    printf("const uint8_t %s[] = {\n", name);

    /*
     * twelve to a line, and a trailing comma on every one of them,
     * both of those are somebody's old decision rather than a
     * requirement, and both have to be kept, because matching the
     * python byte for byte is the whole way this swap is checked
     */
    unsigned char byte[12];
    size_t n;
    while ((n = fread(byte, 1, sizeof byte, f)) > 0) {
        printf("    ");
        for (size_t i = 0; i < n; i++) {
            printf("0x%02x%s", byte[i], i + 1 < n ? ", " : "");
        }
        printf(",\n");
    }
    fclose(f);

    printf("};\n");
    printf("\n");
    printf("const size_t %s_size = sizeof %s;\n", name, name);
    return 0;
}
