#!/usr/bin/env python3
"""turn a flat binary into a C array.

    usage: bin2c.py <name> <in.bin> > out.c

used for the code a second cpu wakes up in. that code has to be sitting
at a fixed low address in real mode, which is nowhere the linker will
put anything, so it is assembled separately and carried inside the
kernel as bytes until it is needed.
"""

import os
import sys

if len(sys.argv) < 3:
    sys.exit(__doc__)

name = sys.argv[1]
blob = open(sys.argv[2], 'rb').read()

print('/* generated by tools/bin2c.py from %s, do not edit */'
      % os.path.basename(sys.argv[2]))
print('#include <stddef.h>')
print('#include <stdint.h>')
print()
print('const uint8_t %s[] = {' % name)
for i in range(0, len(blob), 12):
    row = ', '.join('0x%02x' % b for b in blob[i:i + 12])
    print('    %s,' % row)
print('};')
print()
print('const size_t %s_size = sizeof %s;' % (name, name))
