#!/usr/bin/env python3
# bdf -> C array converter for the console font.
#
#   usage: font2c.py spleen-8x16.bdf > ../kernel/drivers/font.c
#
# only handles fixed 8x16 cell fonts because thats all the console needs.
# glyphs for codepoints 0..255 get taken (ascii + latin1), the rest of
# unicode is somebody elses problem. missing glyphs come out blank.

import sys

LICENSE_HEADER = """\
/* console font: Spleen 8x16 by Frederic Cambus
 * https://github.com/fcambus/spleen
 *
 * Copyright (c) 2018-2026, Frederic Cambus
 * All rights reserved.
 *
 * Redistributed under the BSD 2-Clause license, see the FONT-LICENSE
 * file in the repo root for the full text.
 *
 * this file is GENERATED by tools/font2c.py, dont edit it by hand
 */
"""

def parse_bdf(path):
    glyphs = {}
    encoding = None
    rows = None
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("ENCODING "):
                encoding = int(line.split()[1])
            elif line == "BITMAP":
                rows = []
            elif line == "ENDCHAR":
                if encoding is not None and 0 <= encoding <= 255 and rows:
                    if len(rows) != 16:
                        sys.exit(f"glyph {encoding} has {len(rows)} rows, expected 16")
                    glyphs[encoding] = rows
                encoding = None
                rows = None
            elif rows is not None:
                rows.append(int(line, 16))
    return glyphs

def main():
    if len(sys.argv) != 2:
        sys.exit("usage: font2c.py <font.bdf>")

    glyphs = parse_bdf(sys.argv[1])

    print(LICENSE_HEADER)
    print('#include "font.h"')
    print()
    print("const uint8_t console_font[256][16] = {")
    for cp in range(256):
        rows = glyphs.get(cp, [0] * 16)
        name = chr(cp) if 32 <= cp < 127 else "."
        body = ", ".join(f"0x{b:02x}" for b in rows)
        print(f"    /* 0x{cp:02x} '{name}' */ {{ {body} }},")
    print("};")

if __name__ == "__main__":
    main()
