// SPDX-License-Identifier: GPL-2.0-only
/*
 * tools/gensyms.c
 * Jose A. Perez de Azpillaga <azpijr@gmail.com>, 2026
 * the kernel's function symbols, as a C table, so a panic can say
 * `kmain+0x42` instead of making somebody run addr2line by hand.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#define SHF_EXECINSTR 0x4
#define SHT_SYMTAB    2

struct shdr {
    uint32_t name, type;
    uint64_t flags, addr, offset, size;
    uint32_t link, info;
    uint64_t align, entsize;
};

struct sym {
    uint32_t name;
    uint8_t  info, other;
    uint16_t shndx;
    uint64_t value, size;
};

struct found {
    uint64_t addr;
    char     name[192];
};

static struct found found[16384];
static int count;

static uint8_t *slurp(const char *path, size_t *len)
{
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        fprintf(stderr, "gensyms: cannot read %s\n", path);
        exit(1);
    }
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t *data = malloc((size_t)n);
    if (data == NULL || fread(data, 1, (size_t)n, f) != (size_t)n) {
        fprintf(stderr, "gensyms: %s would not read\n", path);
        exit(1);
    }
    fclose(f);
    *len = (size_t)n;
    return data;
}

/* every symbol that lives in executable memory. */
static void read_symbols(const char *path)
{
    size_t len;
    uint8_t *data = slurp(path, &len);
    if (len < 64 || memcmp(data, "\177ELF", 4) != 0) {
        fprintf(stderr, "gensyms: %s is not an ELF\n", path);
        exit(1);
    }
    uint64_t shoff = *(uint64_t *)(data + 40);
    uint16_t shnum = *(uint16_t *)(data + 60);
    struct shdr *sh = (struct shdr *)(data + shoff);

    for (uint16_t i = 0; i < shnum; i++) {
        if (sh[i].type != SHT_SYMTAB) {
            continue;
        }
        struct sym *syms = (struct sym *)(data + sh[i].offset);
        size_t n = sh[i].size / sizeof *syms;
        const char *str = (const char *)(data + sh[sh[i].link].offset);

        for (size_t k = 0; k < n; k++) {
            uint16_t where = syms[k].shndx;
            if (where == 0 || where >= shnum) {
                continue;
            }
            if (!(sh[where].flags & SHF_EXECINSTR)) {
                continue;
            }
            const char *name = str + syms[k].name;
            if (name[0] == '\0') {
                continue;
            }

            /* several names can share an address. */
            int at = -1;
            for (int q = 0; q < count; q++) {
                if (found[q].addr == syms[k].value) {
                    at = q;
                    break;
                }
            }
            if (at >= 0) {
                if (strcmp(name, found[at].name) < 0) {
                    snprintf(found[at].name, sizeof found[at].name, "%s", name);
                }
                continue;
            }
            if (count >= (int)(sizeof found / sizeof found[0])) {
                continue;
            }
            found[count].addr = syms[k].value;
            snprintf(found[count].name, sizeof found[count].name, "%s", name);
            count++;
        }
    }
}

static int by_address(const void *a, const void *b)
{
    const struct found *x = a, *y = b;
    if (x->addr != y->addr) {
        return x->addr < y->addr ? -1 : 1;
    }
    return strcmp(x->name, y->name);
}

static void emit(void)
{
    qsort(found, (size_t)count, sizeof found[0], by_address);

    printf("/* GENERATED by tools/gensyms.py, do not edit, do not commit */\n");
    printf("#include \"lib/ksyms.h\"\n\n");
    printf("__attribute__((section(\".ksyms\"), used))\n");
    printf("const struct ksym ksym_table[] = {\n");

    /* where each name's text begins in the blob below. */
    static size_t off[sizeof found / sizeof found[0]];
    size_t at = 0;
    for (int i = 0; i < count; i++) {
        off[i] = at;
        at += strlen(found[i].name) + 1;
    }
    for (int i = 0; i < count; i++) {
        size_t use = off[i];
        for (int j = i + 1; j < count; j++) {
            if (strcmp(found[i].name, found[j].name) == 0) {
                use = off[j];
            }
        }
        printf("    { 0x%016llxull, %zu },   /* %s */\n",
               (unsigned long long)found[i].addr, use, found[i].name);
    }
    printf("};\n\n");
    printf("__attribute__((section(\".ksyms\"), used))\n");
    printf("const char ksym_names[] =\n");
    for (int i = 0; i < count; i++) {
        printf("    \"%s\\0\"\n", found[i].name);
    }
    printf("    ;\n\n");
    printf("__attribute__((section(\".ksyms\"), used))\n");
    printf("const unsigned long ksym_count = %d;\n", count);
}

static void stub(void)
{
    printf("/* GENERATED stub for the first link pass */\n");
    printf("#include \"lib/ksyms.h\"\n");
    printf("__attribute__((section(\".ksyms\"), used))\n");
    printf("const struct ksym ksym_table[1];\n");
    printf("__attribute__((section(\".ksyms\"), used))\n");
    printf("const char ksym_names[1];\n");
    printf("__attribute__((section(\".ksyms\"), used))\n");
    printf("const unsigned long ksym_count = 0;\n");
}

/* did folding the table in move anything it claims to describe? */
static int check(const char *elf, const char *generated)
{
    read_symbols(elf);

    size_t len;
    char *text = (char *)slurp(generated, &len);
    int moved = 0;

    for (char *p = text; (p = strstr(p, "{ 0x")) != NULL; ) {
        uint64_t addr = strtoull(p + 4, NULL, 16);
        char *comment = strstr(p, "/* ");
        if (comment == NULL) {
            break;
        }
        char name[192];
        size_t n = 0;
        for (char *q = comment + 3; *q != '\0' && *q != ' ' && *q != '*'
                                    && n + 1 < sizeof name; q++) {
            name[n++] = *q;
        }
        name[n] = '\0';

        const char *now = NULL;
        for (int i = 0; i < count; i++) {
            if (found[i].addr == addr) {
                now = found[i].name;
                break;
            }
        }
        if (now == NULL || strcmp(now, name) != 0) {
            if (moved == 0) {
                fprintf(stderr, "the symbol table went stale, linking it "
                        "in moved these:\n");
            }
            if (moved < 10) {
                fprintf(stderr, "  %#llx was %s, is now %s\n",
                        (unsigned long long)addr, name,
                        now != NULL ? now : "None");
            }
            moved++;
        }
        p = comment;
    }

    if (moved > 0) {
        fprintf(stderr, "\n.ksyms is supposed to sit after .text so this "
                "cannot happen. check linker.ld.\n");
        return 1;
    }
    return 0;
}

int main(int argc, char **argv)
{
    if (argc == 2 && strcmp(argv[1], "--stub") == 0) {
        stub();
        return 0;
    }
    if (argc == 4 && strcmp(argv[1], "--check") == 0) {
        return check(argv[2], argv[3]);
    }
    if (argc != 2) {
        fprintf(stderr, "usage: gensyms <kernel.elf> | --stub | "
                "--check <elf> <generated.c>\n");
        return 2;
    }
    read_symbols(argv[1]);
    emit();
    return 0;
}
