#!/usr/bin/env python3
# turn the kernel's function symbols into a C table, so a panic can say
# "kmain+0x42" instead of making you run addr2line by hand.
#
# this is the same trick tools/font2c.py plays with the console font:
# take something the build already knows and bake it into the image.
#
#   usage: gensyms.py bin/velvetos.pass1 > obj/ksyms.c
#          gensyms.py --check bin/velvetos obj/ksyms.c
#
# the --check mode exists because of the chicken and egg: the table
# records addresses, and linking the table in changes addresses. I
# dodge that by placing .ksyms after .text in the linker script, so
# folding it in shifts .data but never moves a function. --check proves
# that actually held rather than assuming it.

import re
import subprocess
import sys

# nm type letters worth keeping: text, local text, weak
FUNC_TYPES = set('TtWw')

def symbols(elf):
    out = subprocess.run(['nm', '--defined-only', elf],
                         capture_output=True, text=True, check=True).stdout
    syms = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) != 3:
            continue
        addr, kind, name = parts
        if kind not in FUNC_TYPES:
            continue
        addr = int(addr, 16)
        # several names can share an address; keep the first alphabetically
        # so the output is stable between runs
        if addr not in syms or name < syms[addr]:
            syms[addr] = name
    return sorted(syms.items())

def emit(syms, out):
    names, offsets, blob = [], {}, 0
    for _addr, name in syms:
        offsets[name] = blob
        names.append(name)
        blob += len(name) + 1

    print("/* GENERATED by tools/gensyms.py, do not edit, do not commit */", file=out)
    print('#include "lib/ksyms.h"', file=out)
    print(file=out)
    print("__attribute__((section(\".ksyms\"), used))", file=out)
    print("const struct ksym ksym_table[] = {", file=out)
    for addr, name in syms:
        print(f"    {{ 0x{addr:016x}ull, {offsets[name]} }},   /* {name} */", file=out)
    print("};", file=out)
    print(file=out)
    print("__attribute__((section(\".ksyms\"), used))", file=out)
    print("const char ksym_names[] =", file=out)
    for name in names:
        print(f'    "{name}\\0"', file=out)
    print("    ;", file=out)
    print(file=out)
    print("__attribute__((section(\".ksyms\"), used))", file=out)
    print(f"const unsigned long ksym_count = {len(syms)};", file=out)

def stub(out):
    """an empty table, so the first link has something to resolve against.
    its size doesnt matter, .ksyms sits after .text either way."""
    print("/* GENERATED stub for the first link pass */", file=out)
    print('#include "lib/ksyms.h"', file=out)
    print('__attribute__((section(".ksyms"), used))', file=out)
    print('const struct ksym ksym_table[1];', file=out)
    print('__attribute__((section(".ksyms"), used))', file=out)
    print('const char ksym_names[1];', file=out)
    print('__attribute__((section(".ksyms"), used))', file=out)
    print('const unsigned long ksym_count = 0;', file=out)

def check(elf, generated_c):
    """did folding the table in move anything it claims to describe?"""
    current = dict(symbols(elf))
    claimed = {}
    for m in re.finditer(r'\{ 0x([0-9a-f]+)ull, \d+ \},\s*/\* (\S+) \*/',
                         open(generated_c).read()):
        claimed[int(m.group(1), 16)] = m.group(2)

    moved = []
    for addr, name in claimed.items():
        if current.get(addr) != name:
            moved.append((addr, name, current.get(addr)))

    if moved:
        print("the symbol table went stale, linking it in moved these:",
              file=sys.stderr)
        for addr, was, now in moved[:10]:
            print(f"  {addr:#x} was {was}, is now {now}", file=sys.stderr)
        print("\n.ksyms is supposed to sit after .text so this cannot happen. "
              "check linker.ld.", file=sys.stderr)
        return 1
    return 0

def main():
    if len(sys.argv) == 2 and sys.argv[1] == '--stub':
        stub(sys.stdout)
        return 0
    if len(sys.argv) == 4 and sys.argv[1] == '--check':
        return check(sys.argv[2], sys.argv[3])
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    emit(symbols(sys.argv[1]), sys.stdout)
    return 0

if __name__ == '__main__':
    sys.exit(main())
