#!/usr/bin/env python3
"""write the C file that tells the kernel what its own source hashes to.

the machine ships with its source on the same medium (0.3.26), and the
question that makes that worth anything is not "is there a source tree
here" but "is this the source *this* kernel was built from". nothing on
the medium can answer that on its own: an archive and a kernel sitting
next to each other are two files, and any two files can be put next to
each other.

so the answer is written down at the only moment both halves are in the
same room, this one, between building the archive and linking the
kernel that will carry the number.

sha-1 rather than something newer because the machine already has one,
in kernel/lib/hash.c, checked against python and git by hashcheck.py.
this is not a signature and nothing here is defended against somebody
who means harm: it catches a medium that got half-written, an archive
from a different build, and an image somebody assembled by hand out of
mismatched parts. that is the whole claim.

usage: srcstamp.py <source.tar>   (writes C on stdout)
"""

import hashlib
import sys


def main(path):
    data = open(path, 'rb').read()
    print('/* generated by tools/srcstamp.py, do not edit, and do not')
    print(' * put it in the archive either: a source tree that contains a')
    print(' * hash of itself is a source tree that cannot be built twice */')
    print('#include "fs/source.h"')
    print()
    print('const char source_stamp[41] = "%s";' % hashlib.sha1(data).hexdigest())
    print('const uint64_t source_stamp_bytes = %dull;' % len(data))


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
